### ISSUE TITLE
EventBrite API

### ISSUE THREAD

**Issue by allella** [codeforgreenville/OpenData#11]
http://developer.eventbrite.com/doc/

http://developer.eventbrite.com/doc/organizers/organizer_list_events/

**Comment by smoking-peanuts** [comment]
@allella I also noticed that event bright is deprecating the api that is reference by link http://developer.eventbrite.com/doc/

Found at the announcement at the top
Announcement: This API is deprecated, and Eventbrite has released a new version of our API. See new docs here.
http://developer.eventbrite.com/docs/ 
Will this effect api or the keys that we are gathering?

**Comment by allella** [comment]
@smoking-peanuts Good catch.

I'm going to guess the organizer id/key values won't change between their version 1 and version 2 APIs. I think they would be explicit about changes to a key, but I don't see any notes about changes between the two.

http://developer.eventbrite.com/docs/event-search/

**Comment by allella** [comment]
Pretty Example of the JSON
https://www.eventbriteapi.com/v3/events/10584525601/?token=BKKRDKVUVRC5WG4HAVLT

**Comment by smoking-peanuts** [comment]
@allella I have your # and wanted to know if you might be available to talk today or sometime this week. I have a couple of questions that I believe would be best asked over the phone..

**Comment by allella** [comment]
Trying to see if there's a meeting this week. It seems like there should
be, but nothing on Meetup. Probably best to just do something at the next
gathering.

**Comment by allella** [comment]
For Eventbrite the API key is in the MAIN profile URL

For instance, UpstatePHP uses Eventbrite. So, if you find their organization profile on Eventbrite it has a URL of http://www.eventbrite.com/o/upstatephp-6881540935
Where the 6881540935 is the organization key that would be needed to search for events belonging to that org.

Another example, GSATC
http://www.eventbrite.com/o/gsa-technology-council-98409075
The 98409075 is the API key

**Comment by allella** [comment]
Eventbrite events are included in the newest app from Ed.
https://github.com/codeforgreenville/OpenData/issues/12#issuecomment-345403346

**Comment by allella** [comment]
Closing this issue.

For history, see above. For future conversation see the [eventbrite.com bot](https://github.com/codeforgreenville/upstate_tech_cal_service/issues/4) and Ed's new [upstate_tech_cal_service](https://github.com/codeforgreenville/upstate_tech_cal_service) repo.
