### ISSUE TITLE
OpenSC Planning

### ISSUE THREAD

**Issue by allella** [codeforgreenville/OpenData#26]
*wesseljt* [3:38 PM] hey - so my main project fell through for open data day

[3:38] you good with some help on the geojson data?

*allella* [3:40 PM] Yeah, we're dealing with small data, but there's interesting work to be done.

*wesseljt* [3:41 PM] thats no problem

[3:42] any specific direction you wanted to take it?

*allella* [3:42 PM] Benjamin Young and I plan to finish configuring CloudFlare so we have instant scalability and resiliency on the map layers (GeoJSON). The other idea we've been talking about is building a UI that will allow people to click checkboxes (or some such) and put together a JS embed or an iframe (which we'd host) so they can create a map with ease.

*wesseljt* [3:43 PM] Ok, gotcha.

*allella* [3:43 PM] By "create a map", I mean using one or more of the GeoJSON layers we have

*wesseljt* [3:43 PM] Ok, right.

[3:43] any data enrichment or collection that needs to be done?

*allella* [3:44 PM] The longer-term question is how we'd allow someone to use one or more community-curated map layers along side their own data.  That's not too challenging for someone with programming skills, but not as obvious for the non-programmer

[3:45] Here's a simple example of using multiple Swamp Rabbit Trail layers in Google. Pretty quick to do, but not a trivial thing
https://data.openupstate.org/maps/demo/index2.html (edited)

*wesseljt* [3:47 PM] Ok - cool.

[3:47] so for my less tech savy people I could have them collect more data

[3:47] just via google

[3:47] and the more tech savy can work on the above ^

*allella* [3:48 PM] I suppose so. I sort of feel bad asking people to do just the leg work. Though, getting people to commit to co-maintaining map layers they like would be nice.

*wesseljt* [3:49 PM] Sure. like I wanted to start a new restaurants coming soon in greenville geojson file

*allella* [3:50 PM] Another thing we might consider is if there's an easy replacement for Google spreadsheets. The idea that anybody who knows how to edit a spreadsheet can contribute is a core thing for the project.. If we had something that offered similar spreadsheet style ease of use, with built in authenticate and authorization, and allowed us to easily read the data across the web then there's no reason we need to stay on Google's system.

[3:51] I'm all for data if we have solid maintainers. I've tried to steer the initial project ideas to data that changes infrequently, or even never, so we don't have 55 map layers to maintain when people become uninterested

*wesseljt* [3:52 PM] do we have something that currently converts data from the google spreadsheet into geojson?

[3:52] ^ ya - good call

*allella* [3:52 PM] Yes, the core of the current setup is https://github.com/codeforgreenville/leaflet-google-sheets-template/

[3:52] Built at Open Data Day 2014

*wesseljt* [3:52 PM] ahh, ok.

*allella* [3:53 PM] There's also opportunity to consolidate a few of the existing layers so that would be a relatively easy task for newer folks.

[3:53] For instance, we have two EV charger maps and there's no good reason that can't be one

*wesseljt* [3:54 PM] Yup, I agree.

*allella* [3:55 PM] Another idea is making for basic filtering/querying of the data.  If we had the EV charger map but someone wanted to query for city vs county then that would be a nice thing too.  That may be better left for when we have a more solid approach to storing the data than real time Google spreadsheet parsing, but it's something I could see being a nice feature

*wesseljt* [3:56 PM] Sure. Well… personally I really like GEOJSON in postgres - but we would need a frontend where people could easily upload/modify data

[3:57] also - is 50 people the max size for the open works space?

slackbot APP [3:58 PM] Only visible to you
That looks like a Google Drive link. Do you want us to import it and all future Google Drive links from you?
Yes • Just this once • Not now • Never

*allella* [3:58 PM] The SC Codes student Readme has a lot more info on building the maps
https://github.com/codeforgreenville/leaflet-google-sheets-template/blob/master/SC-CODES-README.md

Also, many of these spreadsheets are public but the URLs we have on file are for the CSV or some such. So, we could straighten out the "Open Data Source" column on https://docs.google.com/spreadsheets/d/1IWsFT1p0ZY-DInfMOFq_gmqpGuKyl5wyBb9VoyoEjRs/edit#gid=0
and make that more visible via https://data.openupstate.org/map-layers (edited)

[3:59] We have something like 55 or 65 chairs on the floor, plus about another dozen orange chairs in openworks.

*wesseljt* [3:59 PM] Ok - cool.

*allella* [4:00 PM] We can figure out tables and chairs for as many people as we need.

*wesseljt* [4:00 PM] excellent. would love to pack it out

*allella* [4:03 PM] We have some of the ideas above at https://github.com/codeforgreenville/OpenData/issues but I'll setup issues and notes for the ones that look doable for the day or the near future.

*wesseljt* [4:04 PM] Cool, sounds good.

**Comment by allella** [comment]
Talked with Rachel from Furman about possibly integrating and syndicating some of their ArcGIS data.

She was also interested in how to use the open source CMV.io to build a web viewer for community asset maps. https://cmv.io/examples.html

**Comment by wesseljt** [comment]
Awesome!

**Comment by allella** [comment]
Created issues based on this info.
