### ISSUE TITLE
Move Spreadsheets to a Consistent Code For Greenville Managed Account

### ISSUE THREAD

**Issue by allella** [codeforgreenville/OpenData#29]
Looking into if Code For America can get us a Google Apps account, or else we could create a Gmail account to do the same.

The hope is to copy all the existing spreadsheets into one place to avoid concerns of maintainers disappearing and losing spreadsheets.

We'd need to give the maintainers full writes to the specific files when they are moved.

**Comment by allella** [comment]
EV Charging Stations and Historic Sites are owned by a CFG Gmail account.

**Comment by allella** [comment]
art-galleries/index.html:        zoom: 14
bike-racks/index.html:        zoom: 12
childrens-parks/index.html:        zoom: 13
city-halls/index.html:        zoom: 11
city-parks/index.html:        zoom: 13
community-gardens/index.html:        zoom: 11
coworking-spaces/index.html:        zoom: 14
dogs/dogshops_layers.html:        zoom: 15
dogs/dogfriendlyshops_layers.html:        zoom: 13
dogs/dogservices_layers.html:        zoom: 13
dogs/dogfriendlybreweries_layers.html:        zoom: 13
dogs/restaurants/index.html:        zoom: 11
dogs/index.html:        zoom: 12
electric-charging-stations/index.html:        zoom: 10
falls-park-benches/index.html:        zoom: 15
farmers-markets/index.html:        zoom: 8
fishing/index.html:        zoom: 10
free-job-training/index.html:        zoom: 12
goodwill-dropoffs/index.html:        zoom: 11
greer/parking/googlemap.html:          zoom: 15,
greer/parking/index.html:        zoom: 15
higher-ed/index.html:        zoom: 11
historic-african-american-churches/index.html:        zoom: 10
historic-mills/index.html:        zoom: 12
historic-sites/index.html:        zoom: 13
libraries/index.html:        zoom: 11
live-theatres/live-theaters1:        zoom: 15
live-theatres/index.html:        zoom: 15
live-theatres/live-theaters:        zoom: 15
live-theatres/LiveTheaters.html:        zoom: 15
mailbox-drop-offs/index.html:        zoom: 15
martial-arts-schools/index.html:        zoom: 15
mice-on-main/index.html:        zoom: 16
music-venues/index.html:        zoom: 11
notable-gravesites/index.html:        zoom: 13
organic-farms/index.html:        zoom: 9
parking-decks/index.html:        zoom: 15
pavilion-recreation-complex-amenities/index.html:        zoom: 16
playgrounds/index.html:        zoom: 10
rec-ball-fields/index.html:        zoom: 11
recreation-baseball-fields/index.html:        zoom: 11
recycling/index.html:        zoom: 10
schools/k-12-ib/index.html:        zoom: 11
solid-waste/index.html:        zoom: 11
starbucks/index.html:        zoom: 11
swamp-rabbit-trail/water-fountains/index.html:        zoom: 11
swamp-rabbit-trail/trail/index.html:        zoom: 12
swamp-rabbit-trail/entrances/index.html:        zoom: 11
swamp-rabbit-trail/parking/index.html:        zoom: 12
swamp-rabbit-trail/mile-markers/index.html:        zoom: 13
tent-camping/index.html:        zoom: 9
trees/index.html:        zoom: 11
walking-trails/index.html:        zoom: 10
wall-murals/index.html:        zoom: 13
waterfalls/index.html:        zoom: 10

**Comment by allella** [comment]
art-galleries/index.html:        center: [ 34.8507212,-82.3985128 ],
bike-racks/index.html:        center: [ 34.8507212,-82.3985128 ],
childrens-parks/index.html:        center: [ 34.8507212,-82.3985128 ],
city-halls/index.html:        center: [ 34.8507212,-82.3985128 ],
city-parks/index.html:        center: [ 34.8507212,-82.3985128 ],
community-gardens/index.html:        center: [ 34.8507212,-82.3985128 ],
coworking-spaces/index.html:        center: [ 34.8507212,-82.3985128 ],
dogs/dogshops_layers.html:        center: [ 34.8507212,-82.3985128 ],
dogs/dogfriendlyshops_layers.html:        center: [ 34.8507212,-82.3985128 ],
dogs/dogservices_layers.html:        center: [ 34.8507212,-82.3985128 ],
dogs/dogfriendlybreweries_layers.html:        center: [ 34.8507212,-82.3985128 ],
dogs/restaurants/index.html:        center: [ 34.8507212,-82.3985128 ],
dogs/index.html:        center: [ 34.8507212,-82.3985128 ],
electric-charging-stations/index.html:        center: [ 34.8507212,-82.3985128 ],
falls-park-benches/index.html:        center: [ 34.8507212,-82.3985128 ],
farmers-markets/index.html:        center: [ 34.8507212,-82.3985128 ],
fishing/index.html:        center: [ 34.8507212,-82.3985128 ],
free-job-training/index.html:        center: [ 34.8507212,-82.3985128 ],
goodwill-dropoffs/index.html:        center: [ 34.8507212,-82.3985128 ],
greer/parking/googlemap.html:          center: uluru
greer/parking/index.html:        center: [  34.938727, -82.227200 ],
higher-ed/index.html:        center: [ 34.8507212,-82.3985128 ],
historic-african-american-churches/index.html:        center: [ 34.8507212,-82.3985128 ],
historic-mills/index.html:        center: [ 34.8507212,-82.3985128 ],
historic-sites/index.html:        center: [ 34.8507212,-82.3985128 ],
libraries/index.html:        center: [ 34.8507212,-82.3985128 ],
live-theatres/live-theaters1:        center: [ 34.8507212,-82.3985128 ],
live-theatres/index.html:        center: [ 34.8507212,-82.3985128 ],
live-theatres/live-theaters:        center: [ 34.8507212,-82.3985128 ],
live-theatres/LiveTheaters.html:        center: [ 34.8507212,-82.3985128 ],
mailbox-drop-offs/index.html:        center: [ 34.8507212,-82.3985128 ],
martial-arts-schools/index.html:        center: [ 34.8507212,-82.3985128 ],
mice-on-main/index.html:        center: [ 34.8507212,-82.3985128 ],
music-venues/index.html:        center: [ 34.8507212,-82.3985128 ],
notable-gravesites/index.html:        center: [ 34.8507212,-82.3985128 ],
organic-farms/index.html:        center: [ 34.8507212,-82.3985128 ],
parking-decks/index.html:        center: [ 34.8507212,-82.3985128 ],
pavilion-recreation-complex-amenities/index.html:        center: [ 34.886144, -82.301778],
playgrounds/index.html:        center: [ 34.8507212,-82.3985128 ],
rec-ball-fields/index.html:        center: [ 34.8507212,-82.3985128 ],
recreation-baseball-fields/index.html:        center: [ 34.8507212,-82.3985128 ],
recycling/index.html:        center: [ 34.8507212,-82.3985128 ],
schools/k-12-ib/index.html:        center: [ 34.8507212,-82.3985128 ],
solid-waste/index.html:        center: [ 34.8507212,-82.3985128 ],
starbucks/index.html:        center: [ 34.853234300,-82.397437900 ],
swamp-rabbit-trail/water-fountains/index.html:        center: [ 34.8507212,-82.3985128 ],
swamp-rabbit-trail/trail/index.html:        center: [ 34.8507212,-82.3985128 ],
swamp-rabbit-trail/entrances/index.html:        center: [ 34.8507212,-82.3985128 ],
swamp-rabbit-trail/parking/index.html:        center: [ 34.8507212,-82.3985128 ],
swamp-rabbit-trail/mile-markers/index.html:        center: [ 34.8507212,-82.3985128 ],
tent-camping/index.html:        center: [ 34.8507212,-82.3985128 ],
trees/index.html:        center: [ 34.8507212,-82.3985128 ],
walking-trails/index.html:        center: [ 34.8507212,-82.3985128 ],
wall-murals/index.html:        center: [ 34.8507212,-82.3985128 ],
waterfalls/index.html:        center: [ 34.8507212,-82.3985128 ],

**Comment by allella** [comment]
@ealdthryth Here's the data for the zoom levels and center points.

**Comment by allella** [comment]
@wmfox3 Here's the data for the zoom levels and center points.

**Comment by allella** [comment]
dogfriendlybreweries_geojson.php
dogfriendlybreweries_layers.html
dogfriendlyshops_geojson.php
dogfriendlyshops_layers.html
dogservices_geojson.php
dogservices_layers.html
dogshops_geojson.php
dogshops_layers.html

**Comment by allella** [comment]
@wmfox3 @ealdthryth 

I realized we'll need the CSV path as part of Drupal data. I started adding some but if you guys have time to do the same as was done with the lat/long and zoom then there's a CSV Path column to accept the values below.

```
art-galleries/       https://docs.google.com/spreadsheets/d/1SMH4cKavNzxvqh2PoL9OX_AFKWbrRYxss5pIZ3Zd_EM/pub?output=csv
bike-racks/       https://docs.google.com/spreadsheets/d/1IQol1Gy8gRbQ0wT5YsO9IF_GazVcfbTx828zT9SvGwI/pub?output=csv
childrens-parks/       https://docs.google.com/spreadsheets/d/1_5vw9i2jVtlRiifceXvJX2xUjXp0I7y6SHKjI6Ck1UI/pub?output=csv
city-halls/       https://docs.google.com/spreadsheets/d/1kEZOI6l2p_WsrVF0BwxGUCzhxVHBnxjVbCNZJAhDsag/pub?output=csv
city-parks/       https://docs.google.com/spreadsheets/d/1wZoAej_AQItYS2h0SU0LakECiDUZP_fTTVTzfpnvbIk/pub?output=csv
community-gardens/       https://docs.google.com/spreadsheets/d/1Gn7SNgSYC5W4QtywrglLFgv626NWJ5Ozpzuprqu_C8U/pub?output=csv
coworking-spaces/       https://docs.google.com/spreadsheets/d/14a8hO2JtBvyq457zfEl7Od187qcfYpdlT2US8mmGFRc/pub?output=csv
dogs/       https://docs.google.com/spreadsheets/d/1autJJNR6y4HcZfIiFEqtfOTS2T6pIozExLZ6wgyNnUQ/pub?gid=0&single=true&output=csv
dogs/dogshops_       https://docs.google.com/spreadsheets/d/1autJJNR6y4HcZfIiFEqtfOTS2T6pIozExLZ6wgyNnUQ/pub?gid=16195898&single=true&output=csv
dogs/dogservices_       https://docs.google.com/spreadsheets/d/1autJJNR6y4HcZfIiFEqtfOTS2T6pIozExLZ6wgyNnUQ/pub?gid=16195898&single=true&output=csv
dogs/dogfriendlyshops_       https://docs.google.com/spreadsheets/d/1autJJNR6y4HcZfIiFEqtfOTS2T6pIozExLZ6wgyNnUQ/pub?gid=630384392&single=true&output=csv
dogs/restaurants/       https://docs.google.com/spreadsheets/d/1z1XWR87iwjotHzgHDFeEij7k3XFyDx_B2R7rWfir_qo/pub?output=csv
dogs/dogfriendlybreweries_       https://docs.google.com/spreadsheets/d/1autJJNR6y4HcZfIiFEqtfOTS2T6pIozExLZ6wgyNnUQ/pub?gid=421615217&single=true&output=csv
electric-charging-stations/       https://docs.google.com/spreadsheets/d/1iEgovwZgYVFQum1tafM7tIhYFDqORW0E979dJusYbBQ/pub?gid=0&single=true&output=csv
falls-park-benches/       https://docs.google.com/spreadsheets/d/1DA_JMq97xLe29QhlI9xUo9z4ssTXqeErKIX4t5AbHy8/pub?output=csv
farmers-markets/       https://docs.google.com/spreadsheets/d/11ChGPkiEkNy2VHF5pQQ0s2M76TmQfO1V0Vh7M9cpzdo/pub?output=csv
fishing/       https://docs.google.com/spreadsheets/d/1ePJrMXDa3vdAlQiG5hmaTII6UEq4csJPYmVelJbLqVQ/pub?output=csv
free-job-training/       https://docs.google.com/spreadsheets/d/1d-oNKCNYnZ-rIjr2ZKaVuAGxYJPmJ4h_jlkmxWOirjo/pub?output=csv
goodwill-dropoffs/       https://docs.google.com/spreadsheets/d/1YGBFp1ui1pMeDiPzwKcRnZFWXIa4ZnsnDIXzuwsHf9M/pub?output=csv
greer/parking/       https://docs.google.com/spreadsheets/d/1AVmYeLW5w0SjrjaZNCOZ3yTFzygoHrbnaBgk5A7Px4k/pub?output=csv
higher-ed/       https://docs.google.com/spreadsheets/d/e/2PACX-1vTc4eFPEOuVAIyGWFO7AWOWQbvTcQ9gSymsl8B6orlWdFdWNQnmg0hTkSejJZBT-5aWSLZBWLX1kahb/pub?output=csv
historic-african-american-churches/       https://docs.google.com/spreadsheets/d/1QNJaEdie5Z_Qq4eBIYhj2Guop8KKwGxCfdxMBrF_3WI/pub?output=csv
historic-mills/       https://docs.google.com/spreadsheets/d/1jYNngMxXhrCwvDXM-6JeEwUw23rC_KN9Jn3NPY-o1Sw/pub?output=csv
historic-sites/       https://docs.google.com/spreadsheets/d/1ntx6Kbn48hcy06OGOpkDIPwjl1if7LBDqJGgycc-W6s/pub?gid=0&single=true&output=csv
libraries/       https://docs.google.com/spreadsheets/d/1ZMS5E_GLKI5eb_8KMM46zQIsL55qMAVU50n22tqnUOg/pub?output=csv
live-theatres/       https://docs.google.com/spreadsheets/d/1vqtilaBkI5qtyfGMoF4Cj7qoulLaMRere8Uou4eSui0/pub?output=csv
mailbox-drop-offs/       https://docs.google.com/spreadsheets/d/1D3ClAVV95vzoGfTBdEaFs-0x8djXaj-vJ9awMmbaZP8/pub?output=csv
martial-arts-schools/       https://docs.google.com/spreadsheets/d/1CbO4LyJXLD-Pe9EktvETKps1scWm5TYwpgUIEkCtgCM/pub?output=csv
mice-on-main/       https://docs.google.com/spreadsheets/d/18hpnHdXL1UoUl8UVMDOd4NEoJmNzNOlCSzZiBdfvqso/pub?output=csv
music-venues/       https://docs.google.com/spreadsheets/d/1mtbzu8Rh0YhYcHPrW-kmqcQBAZZBB0abkWVhVpQ7bJ8/pub?output=csv
notable-gravesites/       https://docs.google.com/spreadsheets/d/1PTSm1kHJzPrn5uS3X4Zet5Z6GX2_bs0Ve3AbyvqeXEM/pub?output=csv
organic-farms/       https://docs.google.com/spreadsheets/d/1d-p3Sk73zW9mk_omhv-NLBIiLq3D4UGcPMIXjkH_WcU/pub?output=csv
parking-decks/       https://docs.google.com/spreadsheet/pub?key=1twgxw0fQkv3FlgNrVer16D9LqgTdvibwPBq7KCs8erE&single=true&gid=0&output=csv
pavilion-recreation-complex-amenities/       https://docs.google.com/spreadsheets/d/1MWcOtl8_L3Z-cCqtirFFVZOk6MkdpvhSWD9-IhmApqU/pub?output=csv
playgrounds/       https://docs.google.com/spreadsheets/d/1o38WcipcyIjOdxVHRbiDd9yxifFxog4ppDNedp7EeUc/pub?output=csv
rec-ball-fields/geojson.php://$googleSpreadsheetUrl = "https://docs.google.com/spreadsheet/pub?key=10eNXFh6mzFtii7B2PW90jmHtrQLJlRCrf3kkHU0HIH8&single=true&gid=0&output=csv
rec-ball-fields/       https://docs.google.com/spreadsheets/d/e/2PACX-1vSC45bdLUeEJfh6Vyh5zplV34j2uxyGAKq9FfNaqz5z4i2RugCfnpBlpcXJYIU7x6ThPX6uNmj3XXR1/pub?output=csv
recreation-baseball-fields/       https://docs.google.com/spreadsheets/d/18dSC4azqetSSij9s6EzEcW_2K1OaH_ZOGdK6co4xUGk/pub?gid=0&single=true&output=csv
recycling/       https://docs.google.com/spreadsheets/d/e/2PACX-1vTY14FXEAJH4ahiD_ls5RwmkWHagxPuAnMm8hhOkieIe_-J5U76SNf_EMOm8QJ29LY63tg9PvV19dqX/pub?output=csv
schools/k-12-ib/       https://docs.google.com/spreadsheets/d/e/2PACX-1vQWQJIkVIKhELcSvPAG8jxy-EGf-Gs8rCGVyz8R7y0uW9xMzlR2zKL9ZoNRkyvaZfWy1SttNOT_Q66p/pub?output=csv
solid-waste/       https://docs.google.com/spreadsheets/d/e/2PACX-1vQn9bFgDx3oQ6JmhF6lMFyyK7fTT4HLjjMOJycXPP8hR-XyRv_N2-b_rbL21pCxTutmbyCzOkzwBap8/pub?output=csv
starbucks/       https://docs.google.com/spreadsheets/d/1hxLKBEuJSKuLu_-BwDm55oP5fZ6hcutBqRrzIzMJt5w/pub?output=csv
swamp-rabbit-trail/water-fountains/       https://docs.google.com/spreadsheets/d/1Buqgpbn3qPqFITTf4pn8ISeDVL73D7OyBIdyMfCw7Og/pub?output=csv
swamp-rabbit-trail/trail/       https://docs.google.com/spreadsheets/d/1NfD6eZNs_tPJ3C69Eh9UaPSCebJ_n392ncDDf6U84e4/pub?output=csv
swamp-rabbit-trail/entrances/       https://docs.google.com/spreadsheets/d/1Na4Radl48Qot1BKD6KzaAPvL5cGL-2k3clZV3MWAZOg/pub?output=csv
swamp-rabbit-trail/parking/       https://docs.google.com/spreadsheets/d/e/2PACX-1vQONKh4LNSB4WnpAh-uabPsHzGbwDOiVK3QhA3eCOhueLpJ4-ZacG6wVwEvIC42hsOdGtkHzi2fk5nu/pub?output=csv
swamp-rabbit-trail/mile-markers/       https://docs.google.com/spreadsheets/d/e/2PACX-1vTnh_TrYnHvr4K3rml73kuHIqyHMjmjVk1K7EVWa4EZYfVb2aoE0XcszgM-agPB6cBUimlXOmNcb1GU/pub?output=csv
tent-camping/       https://docs.google.com/spreadsheets/d/1sK9VCoGU2THR8biSD6lCKZ_vUkXIeaEacV8mGEKGN0o/pub?output=csv
trees/       https://docs.google.com/spreadsheets/d/1NfD6eZNs_tPJ3C69Eh9UaPSCebJ_n392ncDDf6U84e4/pub?output=csv
walking-trails/       https://docs.google.com/spreadsheets/d/17Iuvtizyjujqu0w71D7POdCN-cqul_88BYXc1g228gk/pub?output=csv
wall-murals/       https://docs.google.com/spreadsheets/d/1JQ9UZXcIiJJ7zSTEDMxS44waGuAz7jYhkGCTkCgg0pA/pub?output=csv
waterfalls/       https://docs.google.com/spreadsheets/d/e/2PACX-1vRdLwUz7kzQeFa_SaaRzyryBSJO-NSg9XiIRdYCNUmTMHY52MopNcYO_7pnaTNoMmr_DBVJCO9n9uwI/pub?output=csv
```

**Comment by ealdthryth** [comment]
@allella @wmfox3 I can work on this on Thursday.

**Comment by ealdthryth** [comment]
I have done all of them but dog parks. I wasn't sure what to use for that.

**Comment by allella** [comment]
@edusel 
As a starting point, we're going to copy/paste the titles and maintainer/GitHub links.

https://docs.google.com/spreadsheets/d/1IWsFT1p0ZY-DInfMOFq_gmqpGuKyl5wyBb9VoyoEjRs/edit#gid=0

There's a new map ["entity" content type Drupal](https://www.drupal.org/docs/7/api/entity-api/an-introduction-to-entities).  I'm adding fields but we can be creating basic content "nodes" while I'm extending the definition with new fields.

**Comment by allella** [comment]
@edusel I've already copied the title and maintainer (name and GitHub ULR) from the first row of the spreadsheet.

Here's an example
https://data.openupstate.org/node/56
and if you click the "Edit" tab you'll see the admin side and how the title and maintainer look.

**Comment by allella** [comment]
@edusel That's one I maintain so you could use my name and the URL https://github.com/allella

I'm not sure if I'm going to continue to maintain that list so we may kill it.

**Comment by edusel** [comment]
@allella Sounds good, I'll update it for now, we can decide to kill it later if needed.

**Comment by edusel** [comment]
@alella Two additional maps had little/no data associated with them: 'Tech Meetups' and 'Solid Waste'. I left those off the update, otherwise all the nodes have been created. If you agree, let me know and I'll close this issue.

**Comment by alella** [comment]
A typo bought me here. :smile:

**Comment by allella** [comment]
@edusel I'll figure out the solid waste one.  The Tech meetups is not a map. This spreadsheet originally listed any open data projects so that's why it's in there.  We'll be removing the map layers from that spreadsheet as a result of our work here. At that point we can add just one row to point to the list of available open map data layers and continue tracking existing and new data projects on the corresponding tabs of that sheet.

**Comment by allella** [comment]
@edusel I've copied the Solid Waste spreadsheet to a Code For Greenville account so we're able to edit it.

A node for it is at https://data.openupstate.org/map/solid-waste

I'll work on filling in the other info.

Thanks

**Comment by edusel** [comment]
@allella Thanks for the heads up! I'll check it out tonight after work.

**Comment by edusel** [comment]
@allella fyi...i'm not able to login to the site any longer.

**Comment by allella** [comment]
I was able to use the API to update all the existing map nodes in Drupal.

Some of the preview and JSON URLs are not going to work until we complete https://github.com/codeforgreenville/OpenData/issues/37
so that's my next goal.

**Comment by allella** [comment]
Closing this issue. We can continue conversations on #37 and #42
