### ISSUE TITLE
Fix Links to Inaccessible Google Maps Spreadsheets

### ISSUE THREAD

**Issue by allella** [codeforgreenville/OpenData#31]
Some of the links in Column C are not accessible to the public.

https://docs.google.com/spreadsheets/d/1IWsFT1p0ZY-DInfMOFq_gmqpGuKyl5wyBb9VoyoEjRs/edit#gid=0

**Comment by ealdthryth** [comment]
These give message "Sorry, the file you have requested does not exist."
Higher Education -Lauren Hickey
These give message "You need permission"
City Parks - Points - James Aaron
Bike Racks - Amy Lochridge
Dog Parks - JeriBeth
Dog Services - JeriBeth
Dog-friendly Stores (retail) - JeriBeth
Dog-friendly Breweries - JeriBeth
Swamp Rabbit Trail - Convenient Parking - Leland James
Greenville Co. Rec. Baseball/Softball Fields - Jami Mercer
Recycling Locations - Maria Taborda
Notable Gravesites - Michael Crumpler
Live Theatres - Stephen Hill

**Comment by allella** [comment]
JeriBeth is at the event so we can ask here to give the correct links.

**Comment by ealdthryth** [comment]
These are csv links:
Children's Park Locations - Jason Desmond
Dog-friendly Restaurants - Veronica Caruso
Farmers Markets - Victoria Zambrano
Free Job Training Resources in Greenville - Liz Meeker Murphy
Goodwill Drop Off Locations - Gabriel Aragon
Fishing Access Sites-Chris Sweeney
Swinging Benches/Benches in Falls Park -Stephen Bennett
City Hall Locations - Greenville County- Octavia Frazile
Music Venues - Greenville County- Julie Brett
Art Galleries - Walker Reed
Mice on Main Locations- Creighton Magoun
CoWorking Spaces- Brett Brading
Historical African-American Churches -Justin Lewis

**Comment by allella** [comment]
@ealdthryth I was able to convert some of the CSV links over to spreadsheet links by removing the CSV part off the end.  I'll reach out to the other folks about sharing their spreadsheets.

**Comment by allella** [comment]
@ealdthryth Thanks for knocking this out. That's a big help for next steps.

**Comment by allella** [comment]
@ealdthryth I've reached out to all the remaining CSV URL maintainers.

**Comment by allella** [comment]
We should have all but these two working in read-only spreadsheet mode. I'm awaiting replies.

Dog-friendly Restaurants - Veronica Caruso
Historical African-American Churches -Justin Lewis

**Comment by allella** [comment]
Veronica's map layer is know up to date.

@jlew1914 could you mark the spreadsheet for your SC Codes project as view-only to the public and give us a heads up so we can update the directory of public data?

Thanks,
Jim
