### ISSUE TITLE
Nvite API

### ISSUE THREAD

**Issue by allella** [codeforgreenville/OpenData#32]
@nullvariable Do they have an API?

**Comment by nullvariable** [comment]
nvite doesn't have a documented api at present.

However, they do use a JSON api to build much of their page content and it does look like you could leverage that externally.

You can get the most recent event by doing a HEAD request and parsing out the last segment of the redirect url in the header. Like: `https://nvite/<organizer name>` (currently always redirects to the most recent event)

You can then pull data about that event by hitting these JSON endpoints: 
- `https://api.nvite.com/events/<event id>`
- `https://api.nvite.com/events/<event id>/meta`

**Comment by agautsc** [comment]
They also got bought by Eventbrite. Might want to check EB APIs and see if
they have some info there.

**Comment by allella** [comment]
Closing this issue.

For history, see above. For future conversation see the [Nvite.com API bot](https://github.com/codeforgreenville/upstate_tech_cal_service/issues/6) and Ed's new [upstate_tech_cal_service](https://github.com/codeforgreenville/upstate_tech_cal_service) repo.
