### ISSUE TITLE
Working with the City of Greenville

### ISSUE THREAD

**Issue by wmfox3** [codeforgreenville/OpenData#38]
As I've mentioned to some of you, I have opened discussions with the city regarding gaining access to more of their databases as part of what I see as a broader initiative to make Greenville a Data-Smart City. I had an initial meeting June 28 with Government Relations Manager Julie Horton. Later that day, Julie texted me to say that City Manager John Castile "is really interested in talking to you." I followed up with an email that she forwarded to Castile and as a result we've set up a meeting at City Hall at 2 pm on July 10. If anyone is interested in attending the meeting with me, let me know. I see this initial meeting as fact-finding discussion to learn more about how we can help the city and they can help us. Here's the June 28 email:

Julie,

Thanks for taking the time to meet with me today. 

Greenville was built by visionary leaders who sketched a blueprint for its future leading to innovative solutions that addressed anticipated change. Public-private partnerships, respect for the environment and a dedication to finding solutions for housing, jobs, healthcare and education have made Greenville what it is today. In many ways, Greenville was a Smart City before anyone began using that term.

I’m proposing a collaboration with Code for Greenville, a volunteer group organized under the Code for America banner, to use data and technology to make Greenville a Data-Smart City.

I imagine a way residents can get a transparent view of how their city is working for them, and a way for city leadership and department heads to measure their progress toward goals, ensure that resources are aligned with priorities, and taxpayer funds are being spent efficiently. 

This data-infused tool could assist in making decisions regarding the deployment of resources and identify areas of underserved needs. It could ultimately be predictive by anticipating potential issues or challenges before they arise or prior to becoming intractable problems. 

Importantly, this will require building relationships in and across departments, understanding their needs, and identifying opportunities where data can empower and transform. With the right data and agreement on how to measure effectiveness, a variety of internal and external dashboards could be developed. 

Public-facing views of the data could promote a sense of accountability and create channels of engagement and dialogue. 

And the open-sourcing of much, if not most, of this data presents opportunities for the local developer community to use the data as a foundation upon which to build their own civic applications, i.e. the Trolley Tracker. http://trackthetrolley.com/

Cities like Chicago and Boston, and as close as Charlotte and Atlanta, are using data and dashboard displays to track performance in priority areas like housing, neighborhood development, community safety, transportation, economic development and the environment, according to news coverage. 

In my vision, the development work would be done by Code for Greenville volunteers under the auspices of the city at no cost to taxpayers. In exchange, the city would make available datasets and real-time data under agreed-upon terms of use. In other words, while one of the overarching objectives of the project is the make data freely available to the public, I understand that some data might be considered proprietary or not freely distributable. 

I’d love to find a mutually agreeable time to meet with interested city officials to discuss these ideas. I’m including some helpful links to online articles that explore the idea of Data-Smart Cities.

Bill

https://data.boston.gov/
https://data.cityofchicago.org/
http://datasmart.ash.harvard.edu/

**Comment by ajhodges** [comment]
I don't think I can make that meeting but I've just gotta give you major props for taking this initiative, it's really exciting!! I think we would all love to work more closely with the city and hopefully take on some really neat projects and bring a lot more value to the community.

**Comment by jeremywight** [comment]
Excellent @wmfox3! I have it on my calendar!

**Comment by randomjohn** [comment]
Hi,

I had a discussion a few months ago at Furman, and I think they would love to support this kind of initiative. I think some institutional support would provide some stability and even (it’s too early to guarantee this) some infrastructure.

I think that some folks in the data science group would be interested too, so I’ll mention that this initiative at the meeting tonight.

**Comment by jeremywight** [comment]
Thanks John! Yeah would be awesome to get a solid group of invested people
to join in!

**Comment by allella** [comment]
Sounds good @wmfox3.  I'll plan to attend the City Hall at 2 pm on July 10.

**Comment by wmfox3** [comment]
Would it be worth it for @jeremywight, @allella and I to get together between now and July 10 to walk through the initiative? I think it's vitally important that the three of us are on the same page when we meet with Castile. I'm planning to put together some material we can share with the city. Though I see this as an early exploratory session, my initial feedback suggests the city is extremely interested.

**Comment by jeremywight** [comment]
I like the idea of coordinating the communication @wmfox3. I could meet for
lunch downtown on Thursday 7/6 at 12:30, or could do a call if that's
easier.

**Comment by allella** [comment]
I'm glad to talk ahead of time and figure out a strategy.  It would be good to get @randomjohn or @randomjohn involved early too to see what level of involvement/commitment they and their data analytics group could offer if we get useful info out of the City.

@pamelawoodbrowne has also made connections with Furman and the City on the iMAP project but it sounds like those meetings will come after these ones.

**Comment by allella** [comment]
Meant to say @randomjohn or @wesseljt

**Comment by wmfox3** [comment]
7/6 at 12:30 works for me. Open to suggestions on where to eat. It would be helpful if everyone looked at the links I provided the city in my email, as well as https://performance.chattanooga.gov/, which the city was already looking to replicate. Also, @allella, I've noticed many of these Data-Smart City projects are using https://socrata.com/, which might provide an answer to our questions of scalability.

**Comment by allella** [comment]
Let me know where you guys end up. I have a lunch at 11:30 so I'll probably be a bit late.

**Comment by randomjohn** [comment]
I think this is a great idea, though I’m not really available to do anything until after 1:30 pm or so on Thursday (or potentially 1pm if we do a call instead).

**Comment by wmfox3** [comment]
What's the verdict on our lunch location? I'm downtown this morning so anything downtown will be convenient for me.

**Comment by jeremywight** [comment]
Honey Tupelo Cafe work @wmfox3? If not I'm down for GB&D but that's a bit
out of downtown

**Comment by allella** [comment]
I'll probably be there a few minutes late so get started without me and
I'll showup when my earlier meeting lets up.

Thanks,
Jim

**Comment by jeremywight** [comment]
Awesome. See you all at Honey Tupelo Cafe shortly!

**Comment by wmfox3** [comment]
Headed to Tupelo Honey now.

**Comment by randomjohn** [comment]
I’m not able to make it downtown today due to work. Let me know if I can do anything.

**Comment by allella** [comment]
John,

It would be great to have you and/or @wesseljt for the meeting with the city manager on Monday July 10th at 2PM at City Hall.  Would you be able to attend?

**Comment by randomjohn** [comment]
I think I can do that. I’m going to try to get out of work for a couple of hours, but it will probably be at 1:30pm so might be cutting it close.

**Comment by randomjohn** [comment]
Hi,

I did confirm that I can attend, though I’m leaving here around 1:30 so will be cutting it close. Do we have a plan to meet there?



From: John Johnson [mailto:johndjohnson@outlook.com]
Sent: Friday, July 7, 2017 12:03 AM
To: codeforgreenville/OpenData <reply@reply.github.com>; codeforgreenville/OpenData <OpenData@noreply.github.com>
Cc: John Johnson <johndjohnson@gmail.com>; Mention <mention@noreply.github.com>
Subject: RE: [codeforgreenville/OpenData] Working with the City of Greenville (#38)

I think I can do that. I’m going to try to get out of work for a couple of hours, but it will probably be at 1:30pm so might be cutting it close.

**Comment by jeremywight** [comment]
I've got a mandatory meeting this afternoon so I'll have a hard stop at
2:45.

**Comment by allella** [comment]
@randomjohn  We plan to meet in the lobby.

@wmfox3 Do you know what floor or room in case John can't meet in the lobby?

**Comment by wmfox3** [comment]
The city has reception in the lobby and require visitors sign in. They will
direct you. My guess is that Castile's office is on the 10th floor. I'm
planning to be in the lobby about 1:50 p.m.

**Comment by allella** [comment]
Wanted to post a high level overview of my notes from the meeting with the City today in case anybody wants to refer back to it, now or later.  Feel free to add other details.

The City is open to suggestions on what data the public might find interesting.

**Potential Areas of Interest Suggested by the City**
- Parking
- Affordable housing
- Woodruff Road

**Mentions of Existing City Data that's Actively Collected**
- Police
- Permits (the idea of monitoring permits and displaying estimates for # of piqued interests)
- Apartments (planned, in progress, built)
- Census
- Procurement time (in the context of data that's collected but yet to be of much value)

The City Manager was also curious on ideas about where it might start on "internet of things" opportunities.

**Comment by jeremywight** [comment]
Was there any action items or next steps discussed after I dropped Jim?

**Comment by randomjohn** [comment]
Hi Jeremy,

I think the next steps are going to be discussed at the CfA meeting on Tuesday, which I plan to attend.

My thought on next strategy (with next steps maybe to be determined “soon” – possibly at CfA meeting) is to create a project with data that’s actively collected, possibly merging with other public data sources (e.g. US Census API), and create a project of immediate and clear value to the city, and which can be public-facing. Ones that come to mind are the affordable housing, the permits, and the parking, but there may be others. In other news, there’s actions to be done looping in the folks at Furman and the data science folk (and I’ve already contacted John @wesseljt<mailto:wesseljt@gmail.com> over Slack). I think there’s going to be some interest and even expertise on the affordable housing issue, though the parking idea may be another immediate “news you can use” kind of initiative that can be quickly done.

I have a few other things I want to do, such as get the Furman folk involved again, and I think Bill left with a few action items as well.

**Comment by jeremywight** [comment]
Thanks John! I unfortunately will be out of town the next two weeks, but
Jim and Pamela will be leading the charge. Thanks again!

**Comment by pamelawoodbrowne** [comment]
Sorry I missed this thread until now! I would definitely have attended the meetings. Love to see the progress being made! I have had great conversations with Furman and I'm waiting to hear about the extent of interest in our involvement in the recently launched iMap project.

**Comment by jeremywight** [comment]
Ahh... Sorry Pamela! I just thought you weren't available :(

**Comment by wmfox3** [comment]
Jim did a good job with the notes he posted. Here are mine, with considerable overlap of John's.

The city is vitally interested in knowing what the public wants to know and what it needs to know. He cited the example of how the city had mismanaged the Food Truck issue that results in considerable blowback on social media.

John threw out five different issues that he couched as priorities for the city.

**Downtown parking issues**
Does the city have a parking issue problem? It seems they certainly do on weekdays during business hours. Monthly parkers fill up the existing city lots. But there is plenty of parking at night. Are there better ways the city can manage their parking inventory and communicate with motorists? During NCAA tournaments at Wellness Arena, nearby lots quickly filled but further away lots did not. _Data: Some data available in real time for parking availability in each city garage, including information on which monthly parkers have parked and when they depart._

**Affordable housing**
The influx of private investment is squeezing out affordable housing and resulting in massive demographic shifts (gentrification). The city commissioned a study that determined it needs 2,500 affordable housing units. Where should those be built? What areas should be targeted for priority? The city wants to make sure this housing goes where it needs to go. _Data: Housing starts, apartment units._ 

**Woodruff Road traffic**
It's a major issue during certain periods of time and no where near the problem of Atlanta or most major metro markets. However, city needs to get a handle on the problem and identify solutions. The issue is complicated because only a portion of Woodruff Road is within the city limits. Data: Traffic studies? Google traffic? 

**City wants to be performance driven**
The city has much data on crime, building permits, apartments, etc. But what should they be doing with it? What kinds of information would be truly useful to residents?

**Census 2020**
New census data will be available in a few years. Can the city managed to ensure they still have two council districts in which minorities account for at least 51%? With non-minorities moving into these districts, that may no longer be possible. To what extent are upwardly mobile minorities moving into traditional non-minority communities/neighborhoods? _Data: Census, home sales, property assessments._

I think @randomjohn is on the right track as far as focus. Public-facing. Aligns with city's priorities. Demonstrates a relatively quick success. Provides measurable service to taxpayers. That said, given the number of resources we can bring to bear on this, it might be worth developing several ideas simultaneously while managing the city's expectations as to what launches and when. 

While we can definitely have follow-up conversations with John Castile and other members of the city, I think the primary action item is to come back to the city with some concrete proposals. My suggestion is that we create separate teams to handle specific aspects, ie data acquisition, data storage and syndication, data analysis/visualization, public-facing views (internal and external), documentation, promotion/marketing, etc. Then, perhaps, there are one or two people overseeing each project. 

Thoughts?

**Comment by allella** [comment]
Nice notes.

We'll continue the conversation next week at CFG and beyond.

It's hard to know which of the ideas that excite the city will excite the volunteers but hopefully we'll find a trolley tracker caliber idea, or two, from these conversations.

**Comment by allella** [comment]
@wmfox3 I know a few folks are out of town tomorrow but wanted to confirm you'll be there
https://www.meetup.com/Code-for-Greenville/events/240482097/

**Comment by wmfox3** [comment]
I'm planning to be there.

**Comment by allella** [comment]
Pamela missed the last meetup so I thought to share a real quick summary.

We talked at length about ideas for City data projects. We decided to narrow down the list of ideas based on various factors:
- what data likely already available from the City in a usable format
- what are folks in the Data Analytics and Code For Greenville groups interested to work on
- what could be a quick project / win
- what is going to be of interest to the public
- what is going to address some of the city's pains or opportunities

Assuming this info is readily available, we felt like parking and permitting should be in consideration as potential ideas that satisfy these qualifiers.

We see the Data Analytics group as a necessary part of these projects so having their buy in on the 1 or 2 ideas that we start with is critical.  They don't meet until September so that may be a bit of a delay in finalizing an idea.

We also talked about segmenting responsibilities on the projects that gain traction. However, if felt like we need to identify the idea and make sure the City can provide what we need before diving too deep into roles and commitments.

I'll defer to @randomjohn and @wmfox3 on further direction, details, and what to do before things are presented to the Data Analytics groups.

**Comment by Nunie123** [comment]
I saw this article and thought of this project: http://www.greenvilleonline.com/story/news/crime/2017/07/25/greenville-police-seek-late-night-solutions-downtown/504339001/

The article describes how downtown is getting rowdier, but they don't want to pull police out of neighborhoods at night to watch the drunk people on Main.  If this is a serious concern for the city, some number crunching on crime data might be valuable. 

Additionally, I'd like it if we could move forward with this project before September. Our last meeting we determined next step would be to have another conversation with the city to find out what data we can get and how to get it. Is this something I can help with?  What specific actions can we take to move the project forward?

**Comment by wmfox3** [comment]
I agree with @Nunie123 that we should not wait until September. I have followed up with the city requesting meetings with stakeholders in the area of building permits and downtown parking for purposes of gathering information regarding data and processes. I'll let everyone know when I've heard back. Below is the text of my email. Cynthia is the City Manager's executive assistant.

Julie and Cynthia,

The Code For Greenville group along with a representative from Greenville's Data Analytics Meetup group discussed the Data Smart City project at a recent group meeting following our discussion with John Castile. Those of us who attended the meeting with Julie and John briefed the group regarding the overall initiative and relayed the information John conveyed. 

The consensus is that we would like to begin work on one or two projects based on the following criteria. 1) the projects align with the city's priorities, 2) they have the potential of saving taxpayer money (or for making the case for the direction of additional resources), and 3) they lend transparency to the citizens of Greenville regarding the work of their city.

The two areas we believe have the highest immediate potential are the building permit process and the downtown parking situation. This work would be divided among a number of teams on our end spanning one or more technology groups actively working in Greenville. They have the added benefit of assisting us in working through a variety of fundamental issues/challenges that would light a path going forward on future collaborations with the city.

My suggestion as a next step is to identify the individuals with the city with detailed knowledge of the processes and data related to building permits and downtown parking. It may be worth arranging an initial meeting for purposes of gaining a general understanding in these two areas, perhaps simultaneously, and then following up with additional discussions to get more details. 

Please let me know whether the city manager or anyone else with the city would like to discuss the initiative further or has specific questions of us regarding these two areas of interest. In the meantime, I'd like to arrange meetings with the relevant individuals with the city who can assist us moving forward in these two areas.

Once we've assembled the necessary information on our end, we will follow up with the City Manager detailing our proposed work before proceeding.

I appreciate your assistance in this matter,

BIll Fox

**Comment by allella** [comment]
Makes sense. I forgot we decided to follow-up with the City on those data sets so by all means do what you can and it will be more to share with the Data Analytics group.

**Comment by pamelawoodbrowne** [comment]
In addition to moving forward with the City, would it work to invite the Data Analytics folks to join us at our August CFG meeting?

**Comment by wmfox3** [comment]
I've heard back from the city. In sum, Castile is excited about moving forward. He likes both the parking and permit projects. They want to put the parking project on hold due to a leadership shuffle in the parking division. In the meantime, he's going to have an initial discussion with some folks regarding the permit project and then get back to us. Stay tuned @allella @pamelawoodbrowne @edusel @Nunie123

**Comment by wmfox3** [comment]
I've set up a meeting with representatives of the city's permitting department. The meeting is scheduled for this Wednesday, Aug. 16, at 2 pm in City Hall. Let me know if you're interested in attending.

**Comment by pamelawoodbrowne** [comment]
I'm interested in attending.

**Comment by randomjohn** [comment]
I can be there (and I'll attend CfG tomorrow night as well)

**Comment by jeremywight** [comment]
Unfortunately I won't be able to make the City Hall meeting, but excited to
hear what comes out of it! See you all tomorrow!

**Comment by wmfox3** [comment]
I'm planning to attend CfG Tuesday night. We can work out the details then.

**Comment by wmfox3** [comment]
I've had to reschedule the meeting with the city to Friday, Aug. 18 at 11 a.m. at City Hall due to a funeral I will be attending. I may not make it to tonight's CfG meeting due to visitation. @pamelawoodbrowne @jeremywight @randomjohn @allella

**Comment by jeremywight** [comment]
Oh man, sorry to hear Bill :(

**Comment by pamelawoodbrowne** [comment]
Sorry to hear that Bill. I should be able to be there Friday.
@wmfox3

**Comment by randomjohn** [comment]
So sorry Bill.

**Comment by randomjohn** [comment]
Hi Bill, @jeremywight<https://github.com/jeremywight> @randomjohn<https://github.com/randomjohn> @allella<https://github.com/allella>

We talked about a few points tonight that should help on Friday. Unfortunately, I will be in NC on Friday so can’t attend, but @pamelawoodbrowne<https://github.com/pamelawoodbrowne> or Christine can probably be there.

There are a few points that we discussed that may help you out on Friday:
o   What data can we look at? For the purpose of saying whether we can use the data. May be good to have conversations with data owners/managers.
o   Low income housing as an alternative to parking - if there is interest
o   Indication of when parking data will be useful/available (maybe next year)
o   Permitting project could be relatively low tech, and we could collect the data for it by developing and maintaining the process.
·   What are the goals for this initiative?
·   Do they want an analysis, or do they want something (e.g. website/application) to help people submit/track?
Anything else you can come up with, of course, to help move forward with one or two “quick win” projects.

**Comment by allella** [comment]
I'm also out of town on Friday.

@randomjohn The original permitting story was to do something like build an estimated # of days in the queue for the various permits so applicants could be notified (website, email, other subscription methods?) so they don't have to call the office wondering how much backlog there is and the average delay.  I know more information would be useful to the business owners but it would be interesting to know how much that solves problems for the city. For instance, if they get a lot of calls it may actually allow them to refer people to a system and save time where permits work faster.

The other thing it might allow is a data point so the city can budget for inspectors based on the load. The City Manager mentioned part of the slowness with some permits is having only 1 inspector in the budget.

**Comment by allella** [comment]
Also, I would agree that once a project is selected it would be very wise to speak with the folks on the ground and avoid a "consultant" perception with the folks who are likely to provide the data and use the systems we'd build.

I had a lot of success working IT by not just talking to management but really spending the most time with people doing the day-to-day work.

I feel like that will come naturally to the CFG folks, but in bigger organizations the culture might try to insulate the ground-level employees for the decision making when they tend to be critical in getting things right.

**Comment by allella** [comment]
Data questions to ask regardless of what data we ask for:

- Frequency
- Format
- Delivery method/protocol
- Privacy concerns
- Limit to # or records or history
