### ISSUE TITLE
Create and add a favicon

### ISSUE THREAD

**Issue by westonbelk** [codeforgreenville/OpenData#40]
The drupal site is currently using the default drupal favicon. A site or organization specific favicon should be created and added to the site.

**Comment by allella** [comment]
Good idea. Now you have a to-do :)

We not have a logo but I suspect you can make a favicon that's just a letter or something else simple and I can upload the new one to Drupal.

**Comment by allella** [comment]
You can upload a global favicon by unchecking the box on the bottom of this page
https://data.openupstate.org/adminy/appearance/settings
and uploading the file

**Comment by westonbelk** [comment]
Uploaded favicon.

![favicon](https://user-images.githubusercontent.com/4086640/28598382-3116bb54-7171-11e7-9db6-280dc38b730d.png)
