### ISSUE TITLE
BCycle API / GBFS Support

### ISSUE THREAD

**Issue by westonbelk** [codeforgreenville/OpenData#41]
Integrate information from the public B-Cycle bike sharing API. 

The base URL for Greenville can be found at https://gbfs.bcycle.com/bcycle_greenville/gbfs.json.

This api is ["publicly available station bike/dock availability information and does not require the use of an API token"](https://www.bcycle.com/gbfs). 

The documentation for GBFS, the General Bikeshare Feed Specification, can be found at https://github.com/NABSA/gbfs.

More information about the Greenville B-Cycle program can be found at https://greenville.bcycle.com/.

**Comment by allella** [comment]
Interesting. Added to the list at
https://docs.google.com/spreadsheets/d/1IWsFT1p0ZY-DInfMOFq_gmqpGuKyl5wyBb9VoyoEjRs/edit#gid=0

**Comment by allella** [comment]
Did you have any ideas to do something with this data?

If so then go for it. If not I suppose we can close this to-do since it's on the list now.

**Comment by randomjohn** [comment]
I got a Python 3 script that can pull the station data and convert it to GeoJSON. If we can get this running on a scheduled basis, this could be, e.g. added as one of the map layers.

**Comment by allella** [comment]
Cool. You have a repo or download link for the script. I may be able to set it up on the data website.

**Comment by randomjohn** [comment]
Repository is at https://github.com/randomjohn/hackathon_2018

The file you want is  
bcyc_to_geojson.py
