### ISSUE TITLE
Open Data Map: Make URL's clickable

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/OpenData#53]
What: In the open map layers when URLs exist they are plain text. We should wrap these in an <a> tag to make them clickable to make it easier to access the details.

Example: https://data.openupstate.org/map/preview/coworking-spaces

![Image 2021-11-02 at 6 28 29 PM](https://user-images.githubusercontent.com/8245600/139960644-07662b97-84f2-4931-9bae-e156cddc5cb7.jpg)

**Comment by allella** [comment]
It's not ideal to do this in the Javascript, but for now it's working and better than no links.

The GeoJSON isn't rendered dynamically, yet.  We'll do these text manipulations at an earlier stage once the GeoJSON output becomes dynamic.

This should work in all other layers and in any of the bullet points, but here's the example used in this issue.
https://data.openupstate.org/map/preview/coworking-spaces

![image](https://user-images.githubusercontent.com/1777776/182777411-9ecb95a8-4af0-46d0-84fd-bd8cca1e2368.png)
